In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3,4,4,2])
a

array([1, 2, 3, 4, 4, 2])

In [3]:
type(a)

numpy.ndarray

In [4]:
a.ndim

1

In [5]:
print("version = ",np.__version__)  # check version

version =  1.26.4


In [6]:
b=np.array([[1,2,3,4,4,2],[1,2,3,4,2,5]])
b

array([[1, 2, 3, 4, 4, 2],
       [1, 2, 3, 4, 2, 5]])

In [7]:
print("dimension = ",b.ndim) # number of dimention check

dimension =  2


In [8]:
print("shape = ",b.shape)  # shape of the array

shape =  (2, 6)


In [9]:
print(b[0])

[1 2 3 4 4 2]


In [10]:
print(b[1,3])

4


In [11]:
print(b[1,0:4]) # using slicing and indexing

[1 2 3 4]


In [12]:
c = np.array([[[3,2,7,9],[7,8,9,2]],[[3,4,1,2],[8,6,7,8]]] , ndmin = 5) # declare number of dimension
print(c)

[[[[[3 2 7 9]
    [7 8 9 2]]

   [[3 4 1 2]
    [8 6 7 8]]]]]


In [13]:
c.ndim

5

In [14]:
c.reshape(2,4,2)

array([[[3, 2],
        [7, 9],
        [7, 8],
        [9, 2]],

       [[3, 4],
        [1, 2],
        [8, 6],
        [7, 8]]])

In [18]:
e = np.array([4,6,7,9])
print(e)
print()
n = e.copy()
print("n:",n)

[4 6 7 9]

n: [4 6 7 9]


In [64]:
n[1]=3
print(n)

[4 3 7 9]


In [65]:
print(e)
print(n)

[4 6 7 9]
[4 3 7 9]


In [68]:
e1 = np.array([4,6,7,9])
print(e1)
n1 = e1.view()
print("n1:",n1)

[4 6 7 9]
n1: [4 6 7 9]


In [69]:
n1[3]=16
print(n1)

[ 4  6  7 16]


In [70]:
print(n1)
print(e1)

[ 4  6  7 16]
[ 4  6  7 16]


In [22]:
# In numpy module sort method is used for sorting the array..
ary=np.array([4,2,7,8,42,-1,-4])
np.sort(ary)

array([-4, -1,  2,  4,  7,  8, 42])

In [29]:
# numpy method "where" here we can use it
print(ary)

condition = ary < 0
# if condition is true then print 0 ..
# if condition is false then print same value in ary..

print(np.where(condition , 0 ,ary))


[ 4  2  7  8 42 -1 -4]
[ 4  2  7  8 42  0  0]


In [34]:
# here we have a " zero() " method for creating the array..
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [35]:
# here we have a " ones() " method for creating the array..
np.ones(5)

array([1., 1., 1., 1., 1.])