In [1]:
import numpy as np
import pandas as pd


In [2]:
from sklearn.datasets import load_breast_cancer

In [3]:
data = load_breast_cancer()

In [4]:
data.data

array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
        1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
        8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
        8.758e-02],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]])

In [5]:
data.feature_names

array(['mean radius', 'mean texture', 'mean perimeter', 'mean area',
       'mean smoothness', 'mean compactness', 'mean concavity',
       'mean concave points', 'mean symmetry', 'mean fractal dimension',
       'radius error', 'texture error', 'perimeter error', 'area error',
       'smoothness error', 'compactness error', 'concavity error',
       'concave points error', 'symmetry error',
       'fractal dimension error', 'worst radius', 'worst texture',
       'worst perimeter', 'worst area', 'worst smoothness',
       'worst compactness', 'worst concavity', 'worst concave points',
       'worst symmetry', 'worst fractal dimension'], dtype='<U23')

In [6]:
pd.DataFrame(np.c_[data.data , data.target])

0      1       2       3        4        5        6        7       8   \
0    17.99  10.38  122.80  1001.0  0.11840  0.27760  0.30010  0.14710  0.2419   
1    20.57  17.77  132.90  1326.0  0.08474  0.07864  0.08690  0.07017  0.1812   
2    19.69  21.25  130.00  1203.0  0.10960  0.15990  0.19740  0.12790  0.2069   
3    11.42  20.38   77.58   386.1  0.14250  0.28390  0.24140  0.10520  0.2597   
4    20.29  14.34  135.10  1297.0  0.10030  0.13280  0.19800  0.10430  0.1809   
..     ...    ...     ...     ...      ...      ...      ...      ...     ...   
564  21.56  22.39  142.00  1479.0  0.11100  0.11590  0.24390  0.13890  0.1726   
565  20.13  28.25  131.20  1261.0  0.09780  0.10340  0.14400  0.09791  0.1752   
566  16.60  28.08  108.30   858.1  0.08455  0.10230  0.09251  0.05302  0.1590   
567  20.60  29.33  140.10  1265.0  0.11780  0.27700  0.35140  0.15200  0.2397   
568   7.76  24.54   47.92   181.0  0.05263  0.04362  0.00000  0.00000  0.1587   

          9   ...     21      22      23       24       25      26      27  \
0    0.07871  ...  17.33  184.60  2019.0  0.16220  0.66560  0.7119  0.2654   
1    0.05667  ...  23.41  158.80  1956.0  0.12380  0.18660  0.2416  0.1860   
2    0.05999  ...  25.53  152.50  1709.0  0.14440  0.42450  0.4504  0.2430   
3    0.09744  ...  26.50   98.87   567.7  0.20980  0.86630  0.6869  0.2575   
4    0.05883  ...  16.67  152.20  1575.0  0.13740  0.20500  0.4000  0.1625   
..       ...  ...    ...     ...     ...      ...      ...     ...     ...   
564  0.05623  ...  26.40  166.10  2027.0  0.14100  0.21130  0.4107  0.2216   
565  0.05533  ...  38.25  155.00  1731.0  0.11660  0.19220  0.3215  0.1628   
566  0.05648  ...  34.12  126.70  1124.0  0.11390  0.30940  0.3403  0.1418   
567  0.07016  ...  39.42  184.60  1821.0  0.16500  0.86810  0.9387  0.2650   
568  0.05884  ...  30.37   59.16   268.6  0.08996  0.06444  0.0000  0.0000   

         28       29   30  
0    0.4601  0.11890  0.0  
1    0.2750  0.08902  0.0  
2    0.3613  0.08758  0.0  
3    0.6638  0.17300  0.0  
4    0.2364  0.07678  0.0  
..      ...      ...  ...  
564  0.2060  0.07115  0.0  
565  0.2572  0.06637  0.0  
566  0.2218  0.07820  0.0  
567  0.4087  0.12400  0.0  
568  0.2871  0.07039  1.0  

[569 rows x 31 columns]

In [7]:
data.target_names

array(['malignant', 'benign'], dtype='<U9')

In [8]:
dataset = pd.DataFrame(np.c_[data.data , data.target] , columns=[list(data.feature_names) + ["target"]])

In [9]:
dataset


mean radius mean texture mean perimeter mean area mean smoothness  \
0         17.99        10.38         122.80    1001.0         0.11840   
1         20.57        17.77         132.90    1326.0         0.08474   
2         19.69        21.25         130.00    1203.0         0.10960   
3         11.42        20.38          77.58     386.1         0.14250   
4         20.29        14.34         135.10    1297.0         0.10030   
..          ...          ...            ...       ...             ...   
564       21.56        22.39         142.00    1479.0         0.11100   
565       20.13        28.25         131.20    1261.0         0.09780   
566       16.60        28.08         108.30     858.1         0.08455   
567       20.60        29.33         140.10    1265.0         0.11780   
568        7.76        24.54          47.92     181.0         0.05263   

    mean compactness mean concavity mean concave points mean symmetry  \
0            0.27760        0.30010             0.14710        0.2419   
1            0.07864        0.08690             0.07017        0.1812   
2            0.15990        0.19740             0.12790        0.2069   
3            0.28390        0.24140             0.10520        0.2597   
4            0.13280        0.19800             0.10430        0.1809   
..               ...            ...                 ...           ...   
564          0.11590        0.24390             0.13890        0.1726   
565          0.10340        0.14400             0.09791        0.1752   
566          0.10230        0.09251             0.05302        0.1590   
567          0.27700        0.35140             0.15200        0.2397   
568          0.04362        0.00000             0.00000        0.1587   

    mean fractal dimension  ... worst texture worst perimeter worst area  \
0                  0.07871  ...         17.33          184.60     2019.0   
1                  0.05667  ...         23.41          158.80     1956.0   
2                  0.05999  ...         25.53          152.50     1709.0   
3                  0.09744  ...         26.50           98.87      567.7   
4                  0.05883  ...         16.67          152.20     1575.0   
..                     ...  ...           ...             ...        ...   
564                0.05623  ...         26.40          166.10     2027.0   
565                0.05533  ...         38.25          155.00     1731.0   
566                0.05648  ...         34.12          126.70     1124.0   
567                0.07016  ...         39.42          184.60     1821.0   
568                0.05884  ...         30.37           59.16      268.6   

    worst smoothness worst compactness worst concavity worst concave points  \
0            0.16220           0.66560          0.7119               0.2654   
1            0.12380           0.18660          0.2416               0.1860   
2            0.14440           0.42450          0.4504               0.2430   
3            0.20980           0.86630          0.6869               0.2575   
4            0.13740           0.20500          0.4000               0.1625   
..               ...               ...             ...                  ...   
564          0.14100           0.21130          0.4107               0.2216   
565          0.11660           0.19220          0.3215               0.1628   
566          0.11390           0.30940          0.3403               0.1418   
567          0.16500           0.86810          0.9387               0.2650   
568          0.08996           0.06444          0.0000               0.0000   

    worst symmetry worst fractal dimension target  
0           0.4601                 0.11890    0.0  
1           0.2750                 0.08902    0.0  
2           0.3613                 0.08758    0.0  
3           0.6638                 0.17300    0.0  
4           0.2364                 0.07678    0.0  
..             ...                     ...    ...  
564         0.2060      

In [10]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 31 columns):
 #   Column                      Non-Null Count  Dtype  
---  ------                      --------------  -----  
 0   (mean radius,)              569 non-null    float64
 1   (mean texture,)             569 non-null    float64
 2   (mean perimeter,)           569 non-null    float64
 3   (mean area,)                569 non-null    float64
 4   (mean smoothness,)          569 non-null    float64
 5   (mean compactness,)         569 non-null    float64
 6   (mean concavity,)           569 non-null    float64
 7   (mean concave points,)      569 non-null    float64
 8   (mean symmetry,)            569 non-null    float64
 9   (mean fractal dimension,)   569 non-null    float64
 10  (radius error,)             569 non-null    float64
 11  (texture error,)            569 non-null    float64
 12  (perimeter error,)          569 non-null    float64
 13  (area error,)               569 non

In [11]:
X = dataset.iloc[:,:-1]
y = dataset.iloc[:,-1]

In [12]:
y

0      0.0
1      0.0
2      0.0
3      0.0
4      0.0
      ... 
564    0.0
565    0.0
566    0.0
567    0.0
568    1.0
Name: (target,), Length: 569, dtype: float64

In [13]:
from sklearn.model_selection import train_test_split


In [14]:
X_train,X_test,y_train,y_test = train_test_split(X,y , test_size = 0.2 , random_state=2020)

#  TRAIN SUPPORT VECTOR MODEL

In [27]:
from sklearn.svm import SVC

In [16]:
sc = SVC(kernel = "rbf")
sc.fit(X_train,y_train)

SVC()

In [17]:
sc.score(X_test,y_test)

0.9122807017543859

#  FEATURE SCALING

In [19]:
from sklearn.preprocessing import StandardScaler

In [20]:
sc = StandardScaler()
sc.fit(X_train,y_train)

StandardScaler()

In [21]:
X_train_sc = sc.transform(X_train)

In [23]:
X_test_sc = sc.transform(X_test)

#  SVC WITH KERNEL POLYNOMIAL

In [33]:
sc1 = SVC(kernel = "poly" , degree=2)
sc1.fit(X_train_sc , y_train)

SVC(degree=2, kernel='poly')

In [34]:
sc1.score(X_test_sc , y_test)

0.8333333333333334

# SVC WITH KERNEL LINEAR

In [35]:
linear_class = SVC(kernel="linear")
linear_class.fit(X_train_sc , y_train)

SVC(kernel='linear')

In [36]:
linear_class.score(X_test_sc,y_test)

0.9649122807017544

#  PREDICT CANCER

In [39]:
patient1 = [17.99,
 10.38,
 122.8,
 1001.0,
 0.1184,
 0.2776,
 0.3001,
 0.1471,
 0.2419,
 0.07871,
 1.095,
 0.9053,
 8.589,
 153.4,
 0.006399,
 0.04904,
 0.05373,
 0.01587,
 0.03003,
 0.006193,
 25.38,
 17.33,
 184.6,
 2019.0,
 0.1622,
 0.6656,
 0.7119,
 0.2654,
 0.4601,
 0.1189]

In [40]:
patient1_sc = sc.transform(np.array([patient1]))
patient1_sc

array([[ 1.14157516, -2.04268291,  1.31822055,  1.02590938,  1.62044096,
         3.42348005,  2.74540674,  2.64970572,  2.34762157,  2.34157979,
         2.47642647, -0.56729422,  2.77495792,  2.4478528 , -0.23516697,
         1.35781809,  0.68489284,  0.64085494,  1.1927004 ,  0.93126314,
         1.94777877, -1.35487239,  2.37210178,  2.06352534,  1.31020065,
         2.82342306,  2.23450433,  2.38372721,  2.86683913,  2.10454451]])

In [42]:
pred= linear_class.predict(patient1_sc)
pred

array([0.])

In [43]:
data.target_names

array(['malignant', 'benign'], dtype='<U9')

In [44]:
if pred[0] == 0:
  print('Patient has Cancer (malignant tumor)')
else:
  print('Patient has no Cancer (malignant benign)')

Patient has Cancer (malignant tumor)


#                      THANK YOU